name: Say Hello

on:
  push:
    branches:
        - "main"

jobs:
  hello_world:
    runs-on: windows-2019
    steps:
        - name: Echo the message
          run: echo "Hola mundo"
        - name: Echo the message
          run: date
        - name: Echo lista
          run: ls -l